validation on css
jairjy/Microverse-105-Design-Teardown pull request #1
Opened 2019-08-30 19:13 UTC by digomes87

2019-08-30 21:21 UTC, samgaco requested changes
#### Hi @digomes87 and @jairjaramillo :hand: 

#### Everything is looking smooth. Just some points to cover before proceeding:

* The footer should contain centered links
* [OPTIONAL] Correct the warnings given to you by the [validator](https://validator.w3.org) when updating the html file

**Work on these changes and submit back for a code review once you are done :+1:** 

#### Regards! :muscle:

2019-08-30 21:21 UTC, samgaco commented on index.htm
> +    <footer></footer>
The footer should contain centered links.

2019-09-02 17:43 UTC, samgaco approved these changes
#### Everything is ok now. Congratulations on the project, it is looking good :+1: You are approved :medal_sports: 

##### You may merge to the master branch and submit the project completion form :stars:

2019-09-02 17:43 UTC, samgaco commented on index.htm
> +    </footer>
Well done :+1:

2019-09-02 17:44 UTC, samgaco approved these changes

2019-09-02 19:07 UTC, jairjaramillo approved these changes
Merging with master

2019-09-02 19:07 UTC, merged